os: linux
dist: focal
language: python

python:
  - "3.8"

env:
  global:
    - REQUIREMENTS="python3,kivy,plyer,speechrecognition,requests,gtts"
    - ANDROID_API=30
    - ANDROID_MINAPI=21

install:
  - sudo apt update -y
  - sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
  - pip3 install --upgrade pip Cython==0.29.36 buildozer

script:
  - yes | buildozer android debug
  - ls -la bin/
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/HeadphoneRecorderApp-0.1-armeabi-v7a-debug.apk" --tag_name "v0.1"
