version: 2.1  # Required CircleCI version

jobs:
  build-apk:  # Define the build job
    docker:
      - image: kivy/buildozer:latest  # Use the Docker image with Buildozer pre-installed
    steps:
      - checkout  # Check out your repository
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade buildozer
            pip install --upgrade cython
      - run:
          name: Clean previous builds
          command: buildozer android clean
      - run:
          name: Build APK
          command: buildozer -v android debug
      - persist_to_workspace:  # Save artifacts for later use
          root: .
          paths:
            - bin/

workflows:
  apk_build:  # Define the workflow
    jobs:
      - build-apk
