version: 2.1

executors:
  android:
    docker:
      - image: kivy/buildozer:latest

jobs:
  build-apk:
    executor: android
    steps:
      - checkout
      - run:
          name: Обновление Buildozer
          command: |
            pip install --upgrade buildozer
            pip install --upgrade cython
      - run:
          name: Очистка Buildozer
          command: |
            buildozer android clean
            rm -rf .buildozer
      - run:
          name: Сборка APK
          command: |
            buildozer -v android debug

      - store_artifacts:
          path: bin/
          destination: apks
