version: 2.1

jobs:
  build-apk:
    docker:
      - image: kivy/buildozer:latest  # Docker-образ с Buildozer
    steps:
      - checkout  # Извлечение репозитория
      
      # Установка необходимых системных инструментов
      - run:
          name: Установка необходимых инструментов
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
      
      # Установка Python-зависимостей
      - run:
          name: Установка Buildozer и Cython
          command: |
            python3 -m pip install --upgrade pip
            pip install --upgrade buildozer cython
      
      # Загрузка Android SDK и настройка окружения
      - run:
          name: Установка Android SDK
          command: |
            wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
            unzip commandlinetools-linux-8512546_latest.zip -d $HOME/android-sdk
            export ANDROID_HOME=$HOME/android-sdk
            export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33"
      
      # Очистка и сборка APK
      - run:
          name: Очистка и сборка APK
          command: |
            buildozer android clean
            buildozer -v android debug
      
      # Сохранение результата
      - persist_to_workspace:
          root: .
          paths:
            - bin/

workflows:
  version: 2
  apk_build:
    jobs:
      - build-apk
