version: 2.1

jobs:
  build-apk:
    docker:
      - image: kivy/buildozer
    steps:
      - checkout
      - run:
          name: Установка дополнительных зависимостей
          command: |
            sudo apt-get update && sudo apt-get install -y \
            python3-pip libffi-dev libssl-dev wget unzip
      - run:
          name: Установка Android SDK и NDK
          command: |
            mkdir -p ~/.buildozer/android/platform
            
            # Скачивание NDK
            wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -O ndk.zip
            unzip ndk.zip -d ~/.buildozer/android/platform
            rm ndk.zip
            
            # Скачивание SDK
            wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk.zip
            mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
            unzip sdk.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
            rm sdk.zip
            
            # Установка SDK компонентов
            yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
            ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
              "platform-tools" \
              "platforms;android-31" \
              "build-tools;31.0.0"
      - run:
          name: Сборка APK
          command: |
            buildozer -v android debug
      - persist_to_workspace:
          root: .
          paths:
            - bin/*.apk

workflows:
  build-and-deploy:
    jobs:
      - build-apk
