version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-33-node
    steps:
      - checkout
      # 1. Install necessary packages for buildozer
      - run:
          name: Install required dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-venv git
            python3 -m pip install --upgrade pip
            python3 -m pip install buildozer
      # 2. Set up Android SDK root
      - run:
          name: Set ANDROID_SDK_ROOT
          command: |
            echo 'export ANDROID_SDK_ROOT=/opt/android-sdk' >> $BASH_ENV
            echo 'export PATH=$PATH:/opt/android-sdk/platform-tools:/opt/android-sdk/tools/bin' >> $BASH_ENV
      # 3. Accept Android SDK Licenses and install platform tools
      - run:
        name: Accept Android SDK Licenses and install platform tools
        command: |
            yes | /opt/android-sdk/tools/bin/sdkmanager --licenses
            yes | /opt/android-sdk/tools/bin/sdkmanager "platform-tools"
      # 4. Configure Buildozer
      - run:
          name: Configure buildozer to skip gradle wrapper
          command: |
            echo "android.gradle_dependencies.use_gradle_wrapper = False" >> buildozer.spec
      # 5. Buildozer Commands
      - run:
          name: Buildozer Build
          command: |
            buildozer -v android debug

      # (Add additional steps for test, deployment as needed)
