version: 2.1

executors:
  android:
    docker:
      - image: kivy/buildozer:latest  # Официальный образ с Python и Buildozer

jobs:
  build-apk:
    executor: android
    steps:
      - checkout
      - run:
          name: Установка зависимостей
          command: |
            sudo apt-get update && sudo apt-get install -y \
              openjdk-8-jdk unzip
            export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
            buildozer android clean
            buildozer -v android debug
      
      - persist_to_workspace:  # Сохранить APK для использования в других задачах или артефактах
          root: .
          paths:
            - bin/

workflows:
  version: 2
  apk-build:
    jobs:
      - build-apk
