version: 2.1

jobs:
  build-apk:
    docker:
      - image: kivy/buildozer:latest
    steps:
      - checkout  # Check out your code
      - run:
          name: Upgrade pip
          command: python3 -m pip install --upgrade pip
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade buildozer cython
            mkdir -p $HOME/android-sdk $HOME/android-ndk
            export ANDROID_HOME=$HOME/android-sdk
            export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH
      - run:
          name: Clean previous builds
          command: rm -rf .buildozer
      - run:
          name: Build APK
          command: buildozer -v android debug
      - persist_to_workspace:
          root: .
          paths:
            - bin/

workflows:
  apk_build:
    jobs:
      - build-apk
