version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
        environment:
          ANDROID_SDK_ROOT: /opt/android-sdk
    resource_class: large
    steps:
      - checkout

      - run:
          name: Install Buildozer and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y git zip unzip openjdk-11-jdk curl
            pip install --upgrade pip
            pip install buildozer cython==0.29.36

      - run:
          name: Install Android Command Line Tools
          command: |
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
            curl --fail --retry 3 -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
            export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
            echo "Accepting SDK licenses"
            yes | sdkmanager --licenses
            yes | sdkmanager --update

      - run:
          name: Install Android SDK Build-Tools
          command: |
            yes | sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33"

      - run:
          name: Build APK
          command: buildozer -v android debug

      - store_artifacts:
          path: bin/
          destination: apk-files
