version: 2.1

jobs:
  build-apk:
    docker:
      - image: kivy/buildozer:latest  # Buildozer image with dependencies
    steps:
      - checkout  # Pull the latest code
      - run:
          name: Clean Buildozer
          command: rm -rf .buildozer
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade buildozer cython
            mkdir -p /opt/android-sdk /opt/android-ndk
      - run:
          name: Build APK
          command: buildozer -v android debug
      - persist_to_workspace:
          root: .
          paths:
            - bin/

workflows:
  apk_build:
    jobs:
      - build-apk
