version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Вы можете изменить версию Python при необходимости
    steps:
      # Шаг 1: Клонирование репозитория
      - checkout

      # Шаг 2: Установка зависимостей для Android SDK
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y git unzip openjdk-11-jdk curl
            pip install --upgrade pip
            pip install buildozer cython==0.29.36

      # Шаг 3: Установка Android Command Line Tools
      - run:
          name: Install Android Command Line Tools
          command: |
            export ANDROID_SDK_ROOT=$HOME/android-sdk
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
            curl --fail --retry 3 -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
            export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
            yes | sdkmanager --licenses
            yes | sdkmanager --update
            yes | sdkmanager --install \
              "platform-tools" \
              "build-tools;33.0.0" \
              "platforms;android-33"

      # Шаг 4: Сборка APK
      - run:
          name: Build APK
          command: |
            export ANDROID_SDK_ROOT=$HOME/android-sdk
            buildozer -v android debug

      # Шаг 5: Сохранение сгенерированного APK в артефакты
      - store_artifacts:
          path: bin/
          destination: apk-files
