version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y git unzip openjdk-11-jdk curl libffi-dev libssl-dev zlib1g-dev build-essential libstdc++6
            pip install --upgrade pip
            pip install "buildozer[debug]" cython==0.29.36
      - run:
          name: Install Android SDK
          command: |
            export ANDROID_SDK_ROOT=$HOME/android-sdk
            mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
            curl --fail --retry 3 -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip -q cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
            mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
            export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.0:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
            { yes || true; } | sdkmanager --licenses
            sdkmanager --update
            sdkmanager --install \
              "platform-tools" \
              "build-tools;33.0.0" \
              "platforms;android-33"
      - run:
          name: Verify AIDL
          command: |
            export PATH=$ANDROID_SDK_ROOT/build-tools/33.0.0:$PATH
            ls $ANDROID_SDK_ROOT/build-tools/33.0.0/aidl
      - run:
          name: Build APK
          command: |
            export ANDROID_SDK_ROOT=$HOME/android-sdk
            export PATH=$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/33.0.0:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
            buildozer -v android debug
      - store_artifacts:
          path: bin/
          destination: apk-files
