version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout

      - run:
          name: Install required dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-venv git openjdk-11-jdk
            python3 -m pip install --upgrade pip
            python3 -m pip install buildozer

      - run:
          name: Set ANDROID_SDK_ROOT
          command: |
            echo 'export ANDROID_SDK_ROOT=/opt/android-sdk' >> $BASH_ENV
            echo 'export PATH=$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Accept Android SDK Licenses
          command: |
            yes | sdkmanager --licenses

      - run:
          name: Install Android SDK Platforms and Tools
          command: |
            sdkmanager --install "platform-tools" "build-tools;30.0.0" "platforms;android-30" "cmdline-tools;latest"

      - run:
          name: Verify AIDL Installation
          command: |
            ls $ANDROID_SDK_ROOT/build-tools/30.0.0/aidl || echo "AIDL not found!"
            $ANDROID_SDK_ROOT/build-tools/30.0.0/aidl --version || echo "AIDL version check failed!"

      - run:
          name: Build APK with Buildozer
          command: |
            buildozer -v android debug

      - store_artifacts:
          path: bin/
          destination: apk-files
