version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:20.04  # Используем базовый образ Ubuntu
    steps:
      - checkout  # Проверка кода

      # 1. Установка зависимостей
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y \
              python3-pip \
              python3-venv \
              git \
              openjdk-11-jdk \
              wget \
              unzip
            python3 -m pip install --upgrade pip
            python3 -m pip install buildozer

      # 2. Установка Android SDK вручную
      - run:
          name: Install Android SDK
          command: |
            mkdir -p /opt/android-sdk && cd /opt/android-sdk
            wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O tools.zip
            unzip tools.zip && rm tools.zip
            mkdir -p cmdline-tools/latest
            mv cmdline-tools/* cmdline-tools/latest
            echo 'export ANDROID_SDK_ROOT=/opt/android-sdk' >> $BASH_ENV
            echo 'export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH' >> $BASH_ENV
            source $BASH_ENV
            yes | sdkmanager --licenses
            sdkmanager --install "platform-tools" "build-tools;33.0.2" "platforms;android-33"

      # 3. Сборка APK через Buildozer
      - run:
          name: Build APK
          command: buildozer -v android debug

      # 4. Сохранение артефактов
      - store_artifacts:
          path: bin/
          destination: apk-files
