version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-33
    steps:
      - checkout

      # 1. Установка необходимых зависимостей для buildozer
      - run:
          name: Install required dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip python3-venv git openjdk-11-jdk
            python3 -m pip install --upgrade pip
            python3 -m pip install buildozer

      # 2. Установка переменной окружения ANDROID_SDK_ROOT
      - run:
          name: Set ANDROID_SDK_ROOT
          command: |
            echo 'export ANDROID_SDK_ROOT=/opt/android-sdk' >> $BASH_ENV
            echo 'export PATH=$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH' >> $BASH_ENV
            source $BASH_ENV

      # 3. Принятие лицензий Android SDK
      - run:
          name: Accept Android SDK Licenses
          command: |
            yes | sdkmanager --licenses

      # 4. Установка платформы Android и Build-Tools
      - run:
          name: Install Android SDK Platforms and Tools
          command: |
            sdkmanager --install "platform-tools" "build-tools;33.0.0" "platforms;android-33" "cmdline-tools;latest"

      # 5. Проверка наличия aidl и других инструментов
      - run:
          name: Verify AIDL Installation
          command: |
            ls $ANDROID_SDK_ROOT/build-tools/33.0.0/aidl || echo "AIDL not found!"
            $ANDROID_SDK_ROOT/build-tools/33.0.0/aidl --version || echo "AIDL version check failed!"

      # 6. Выполнение команды buildozer для сборки APK
      - run:
          name: Build APK with Buildozer
          command: |
            buildozer -v android debug

      # 7. Сохранение собранного APK
      - store_artifacts:
          path: bin/
          destination: apk-files
