version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Используем окружение с Python 3.9
    steps:
      # Шаг 1: Клонирование репозитория
      - checkout
      
      # Шаг 2: Установка Buildozer и необходимых инструментов
      - run:
          name: Install Buildozer and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y git zip unzip openjdk-11-jdk
            pip install --upgrade pip
            pip install buildozer cython==0.29.36
            
      # Шаг 3: Сборка APK
      - run:
          name: Build APK
          command: |
            buildozer -v android debug

      # Шаг 4: Сохранение APK в артефакты CircleCI
      - store_artifacts:
          path: bin/
          destination: apk-files
