version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Buildozer and dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y git zip unzip openjdk-11-jdk curl
            pip install --upgrade pip
            pip install buildozer cython==0.29.36
            export PATH=$HOME/.local/bin:$PATH

      - run:
          name: Install Android Command Line Tools
          command: |
            mkdir -p $HOME/android/cmdline-tools
            curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
            unzip commandlinetools.zip -d $HOME/android/cmdline-tools
            mv $HOME/android/cmdline-tools/cmdline-tools $HOME/android/cmdline-tools/latest
            export PATH=$HOME/android/cmdline-tools/latest/bin:$PATH
            yes | sdkmanager --licenses

      - run:
          name: Install Android SDK Build-Tools
          command: |
            mkdir -p $HOME/.buildozer/android/platform/android-sdk
            yes | sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
              "platform-tools" \
              "build-tools;33.0.0" \
              "platforms;android-33"

      - run:
          name: Build APK
          command: |
            buildozer -v android debug

      - run:
          name: Check bin directory
          command: |
            if [ ! -d "bin/" ]; then
              echo "Directory bin/ does not exist. Check Buildozer logs for errors."
              exit 1
            fi

      - store_artifacts:
          path: bin/
          destination: apk-files
